class AppLocalizationsTr {
  static const Map<String, String> _localizedStrings = {
    'hello': 'Merhaba',
    "Wellcome": 'Hoşgeldiniz',
    "Login now to find your best Match":
        "En iyisini bulmak için şimdi giriş yapın",
    "Password": "Şifre",
    "Email or Password is Missing": "E-posta veya Şifre Eksik",
    "Please fill all  fields.": "Lütfen tüm alanları doldurun.",
    "Login": "Giriş",
    "Don't have an account? ": "Hesabınız yok mu? ",
    "Create Here": "Hemen Oluştur",
    "Create Account": "Hesap Oluştur",
    "to get Started Now": " ",
    "Personal Info:": "Kişisel Bilgiler:",
    "Name": "İsim",
    "Age": "Yaş",
    "Gender": "Cinsiyet",
    "Male": "Erkek",
    "Female": "Kadın",
    "Others": "Diğer",
    "City": "Şehir",
    "Country": "Ülke",
    "Austria": "Avusturya",
    "Brazil": "Brezilya",
    "Canada": "Kanada",
    "China": "Çin",
    "France": "Fransa",
    "Germany": "Almanya",
    "India": "Hindistan",
    "Indonesia": "Endonezya",
    "Italy": "İtalya",
    "Japan": "Japonya",
    "Mexico": "Meksika",
    "Netherlands": "Hollanda",
    "Russia": "Rusya",
    "Saudi Arabia": "Suudi Arabistan",
    "South Korea": "Güney Kore",
    "Spain": "İspanya",
    "Switzerland": "İsviçre",
    "Turkey": "Türkiye",
    "United Kingdom": "İngiltere",
    "United States": "Amerika",
    "Appearance:": "Dış görünüş:",
    "Height": "Boy",
    "Weight": "Kilo",
    "Life Style:": "Yaşam tarzı:",
    "Drink": "İçki",
    "Smoke": "Sigara",
    "Marital Status": "Medeni hal",
    "Profession": "Meslek",
    "Living Situation": "Kiminle Yaşıyorsun",
    "Background-Culturel Values:": "Kültürel Değerler:",
    "Education": "Eğitim",
    "Religion": "Din",
    "Ethnicity": "Millet",
    "A Field is Empty ": "Bir Alan Boş",
    "Please fill out all field in text fields.":
        "Lütfen metin alanlarındaki tüm alanları doldurun.",
    "Image File Missing": "Görüntü Dosyası Eksik",
    "Please pick image from gallery or capture with Camera":
        "Lütfen galeriden resim seçin veya Kamera ile çekin",
    "Already have an account?": "Zaten hesabınız var mı?  ",
    "Login Here": "Giriş yapın",
    "Updating...": "Güncelleniyor...",
    "Updated": "Güncellendi",
    "your account has been updated successful":
        "Hesabınız başarıyla güncellendi",
    "Profile Information": "Profil bilgisi",
    "Error": "Hata",
    "Failed to upload image:": "Resim yüklenemedi:",
    "Update": "Güncelle",
    "Profile Image": "Profil Resmi",
    "you have successfully picked your profile image from gallery":
        "profil resminizi galeriden başarıyla seçtiniz",
    "you have succesfully captured your profile image using camera":
        "kamera kullanarak profil resminizi başarıyla yakaladınız",
    "Account Creation Uns": "Hesap Oluşturma İşlemleri",
    "Error occurred: ": "Hata oluştu: ",
    "Logged in Successful": "Başarılı bir şekilde oturum açıldı",
    "you are logged in successfully.": "Başarıyla giriş yaptınız.",
    "Login Unsuccessful": "Giriş Başarısız",
    'New Message': 'Yeni Mesaj',
    "you have received a new ": "Yeni ",
    "from": "şu kişiden:",
    "Click to see.": "Görmek için tıklayın.",
    "New": "Yeni",
    "My Likes": "Beğendiklerim",
    "Liked Me": "Beni Beğenenler",
    "Messages": "Mesajlar",
    "No messages": "Hiç Mesaj yok",
    "Loading...": "Yükleniyor...",
    "No message": "Mesaj yok",
    "Matching Filter": "Arama Filtresi",
    "I am looking for a:": "Cinsiyet:",
    "Select gender": "Cinsiyet seçimi",
    "who lives in": "Ülke:",
    "Select country": "Ülke Seç",
    "Done": "Uygulama",
    "Swipping Screen": "Kaydırma Ekranı",
    "No profile matching the search criteria was found.":
        "Arama kriterlerine uygun profil bulunamadı.",
    "Reset Filters": "Filtreyi Sıfırla",
    "User ID is not available.": "Kullanıcı kimliği mevcut değil.",
    "Name: ": "İsim: ",
    "Age: ": "Yaş: ",
    "Gender: ": "Cinsiyet: ",
    "City: ": "Şehir: ",
    "Country: ": "Ülke: ",
    "Height: ": "Boy: ",
    "Weight: ": "Kilo: ",
    "Drink: ": "İçki: ",
    "Smoke: ": "Sigara: ",
    "Martial Status: ": "Medeni hal: ",
    "Profession: ": "Meslek: ",
    "Living Situation: ": "Yaşama Durumu: ",
    "Background - Cultural Values:": "Kültürel Değerler: ",
    "Education: ": "Eğitim: ",
    "Religion: ": "Din: ",
    "Ethnicity: ": "Millet: ",
    "Profile i viewed": "Baktığım Profiller",
    "Viewed My Profile": "Profilime Bakanlar",
    "You have a new message.Click here!": "Yeni mesajın var.Tıkla!",
    "This person viewed your profile": "Bu kişi profiline baktı",
    "Chat": "Sohbet",
    "Send": "Gönder",
    "View Profile": "Profile Bak",
    "Close": "Kapat",
    "Delete Account": "Hesabı Sil",
    'Are you sure you want to delete your account? This action cannot be undone.':
        'Hesabınızı silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
    "No": "Hayır",
    "Yes": "Evet",
    "Account Deleted": "Hesap Silindi",
    "Your account has been successfully deleted.":
        "Hesabınız başarıyla silindi.",
    "Mistake": "Hata",
    "An error occurred while deleting the account: ":
        "Hesap silinirken bir hata oluştu: ",
    "Age Requirement Not Met": "Yaş şartı karşılanmıyor",
    "You must be at least 18 years old to register.":
        "Kayıt olmak için en az 18 yaşında olmanız gerekir.",
    "Privacy Policy": "Gizlilik Politikası",
  };

  String translate(String key) {
    return _localizedStrings[key] ?? key;
  }
}
